# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

builddmat <- function(lens, ords, wrap) {
    .Call(`_tflattices_builddmat`, lens, ords, wrap)
}

projnull <- function(D, S) {
    .Call(`_tflattices_projnull`, D, S)
}

phipp <- function(lossfunction, th) {
    .Call(`_tflattices_phipp`, lossfunction, th)
}

etfgrid_c <- function(Y, dimensions, korder, wrap, lossfunction, nsol = 50L, lambdamin = -1, lambdamax = -1, lambda = as.numeric( c()), mu_adjust = -1, rho_adjust = -1, mu = -1, rho = -1, pen_null = 0L, alpha = .1, dfestim = 0L, maxiter = 100L, tolerance = 1e-3, verbose = 0L) {
    .Call(`_tflattices_etfgrid_c`, Y, dimensions, korder, wrap, lossfunction, nsol, lambdamin, lambdamax, lambda, mu_adjust, rho_adjust, mu, rho, pen_null, alpha, dfestim, maxiter, tolerance, verbose)
}

